version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "localhost"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 8888:8080
    network_mode: "host"
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=web"

  api:
    environment:
      # Network
      MEMPOOL_BACKEND: "none"
      
      # Bitcoin Core RPC
      CORE_RPC_HOST: "${CORE_RPC_HOST:-127.0.0.1}"
      CORE_RPC_PORT: "${CORE_RPC_PORT:-8332}"
      CORE_RPC_USERNAME: "${CORE_RPC_USERNAME:-mempool}"
      CORE_RPC_PASSWORD: "${CORE_RPC_PASSWORD:-mempool}"
      CORE_RPC_TIMEOUT: "${CORE_RPC_TIMEOUT:-60000}"
      
      # Database
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      
      # Statistics
      STATISTICS_ENABLED: "true"
      STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD: "150"
      
      # Cache
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      
      # Frontend
      MEMPOOL_WEBSITE_TITLE: "ordinalOS Mempool"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - mempool_cache:/backend/cache
    depends_on:
      - db
    network_mode: "host"
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=api"

  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
    image: mariadb:10.5.21
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - mempool_db:/var/lib/mysql
    networks:
      - default
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=db"

networks:
  default:
    name: coolify
    external: true

volumes:
  mempool_db:
    name: mempool_db
  mempool_cache:
    name: mempool_cache 
