version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8888"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8888:8888"
    networks:
      - default
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=web"

  api:
    environment:
      MEMPOOL_BACKEND: "none"
      CORE_RPC_HOST: "172.17.0.1"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "bitcoin"
      CORE_RPC_PASSWORD: "5cb9655ae8b0254966e46b7bd9046333329d43bf64ff16acaba8b337a72ed8e1"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    network_mode: "host"
    volumes:
      - ./data:/backend/cache
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=api"

  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
    image: mariadb:10.5.21
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default
    labels:
      - "coolify.enable=true"
      - "coolify.version=1"
      - "mempool.type=db"

networks:
  default:
    name: coolify
    external: true 
